"""empty message

Revision ID: 054be0852f9f
Revises: 3df429698f31
Create Date: 2022-02-23 23:40:15.805711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054be0852f9f'
down_revision = '3df429698f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streets', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streets', 'tags')
    # ### end Alembic commands ###
