"""empty message

Revision ID: 0d8c69fb3ae0
Revises: a1fb1a3ff551
Create Date: 2022-03-09 23:58:22.855050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8c69fb3ae0'
down_revision = 'a1fb1a3ff551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_streets_edits_street_id'), 'streets_edits', ['street_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streets_edits_street_id'), table_name='streets_edits')
    # ### end Alembic commands ###
