"""empty message

Revision ID: 3154e83d2e30
Revises: 4ae2f5a7cfc1
Create Date: 2022-06-03 19:45:01.594699

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3154e83d2e30"
down_revision = "4ae2f5a7cfc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annexations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=3435, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annexations_year"), "annexations", ["year"], unique=False)
    op.drop_table("street_lines")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "street_lines",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=3435, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "street_id", sa.VARCHAR(length=25), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="street_lines_pkey"),
    )
    op.drop_index(op.f("ix_annexations_year"), table_name="annexations")
    op.drop_index(
        "idx_annexations_geom",
        table_name="annexations",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_table("annexations")
    # ### end Alembic commands ###
