"""empty message

Revision ID: 521d4d6c0f59
Revises: 
Create Date: 2022-01-24 04:09:10.450246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521d4d6c0f59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.String(length=25), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grid_location', sa.Integer(), nullable=True),
    sa.Column('grid_direction', sa.String(length=2), nullable=True),
    sa.Column('diagonal', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('suffix', sa.String(length=15), nullable=True),
    sa.Column('suffix_direction', sa.String(length=3), nullable=True),
    sa.Column('min_address', sa.Integer(), nullable=True),
    sa.Column('max_address', sa.Integer(), nullable=True),
    sa.Column('current', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('historical_note', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('weird', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('skip', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streets_current'), 'streets', ['current'], unique=False)
    op.create_index(op.f('ix_streets_end_date'), 'streets', ['end_date'], unique=False)
    op.create_index(op.f('ix_streets_name'), 'streets', ['name'], unique=False)
    op.create_index(op.f('ix_streets_start_date'), 'streets', ['start_date'], unique=False)
    op.create_index(op.f('ix_streets_suffix'), 'streets', ['suffix'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('d_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.String(length=20), nullable=False),
    sa.Column('number_prefix', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('number_suffix', sa.String(), nullable=True),
    sa.Column('street_name_pre_directional', sa.String(), nullable=True),
    sa.Column('street_name_pre_type', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('street_name_post_type', sa.String(), nullable=True),
    sa.Column('subaddress_type', sa.String(), nullable=True),
    sa.Column('subaddress_identifier', sa.String(), nullable=True),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('corner_of', sa.String(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('streetchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streets_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr_id', sa.String(length=20), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('suffix_generational', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('spouse_name', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('widow', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('work_address_id', sa.Integer(), nullable=True),
    sa.Column('home_address_id', sa.Integer(), nullable=True),
    sa.Column('telephone_number', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('weird', sa.Boolean(), nullable=True),
    sa.Column('skip', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['home_address_id'], ['d_address.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['work_address_id'], ['d_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('streets_edits')
    op.drop_table('streetchange')
    op.drop_table('roles')
    op.drop_table('pages')
    op.drop_table('d_address')
    op.drop_table('users')
    op.drop_index(op.f('ix_streets_suffix'), table_name='streets')
    op.drop_index(op.f('ix_streets_start_date'), table_name='streets')
    op.drop_index(op.f('ix_streets_name'), table_name='streets')
    op.drop_index(op.f('ix_streets_end_date'), table_name='streets')
    op.drop_index(op.f('ix_streets_current'), table_name='streets')
    op.drop_table('streets')
    op.drop_table('directories')
    # ### end Alembic commands ###
