"""empty message

Revision ID: 84b5ddd15854
Revises: e68b43218263
Create Date: 2022-01-31 03:31:18.672126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b5ddd15854'
down_revision = 'e68b43218263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streets', sa.Column('start_date_circa', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('streets', 'start_data_circa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streets', sa.Column('start_data_circa', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('streets', 'start_date_circa')
    # ### end Alembic commands ###
