"""empty message

Revision ID: 85ff8aa6633e
Revises: f29b30fc0074
Create Date: 2022-04-15 20:52:38.803721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85ff8aa6633e"
down_revision = "f29b30fc0074"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "streets", sa.Column("successor_name", sa.String(length=80), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("streets", "successor_name")

    # ### end Alembic commands ###
