"""empty message

Revision ID: f29b30fc0074
Revises: 0d8c69fb3ae0
Create Date: 2022-03-11 16:16:52.228171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29b30fc0074'
down_revision = '0d8c69fb3ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_streets_name_suff', 'streets', ['name', 'suffix'], unique=False)
    op.create_index(op.f('ix_streets_street_id'), 'streets', ['street_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streets_street_id'), table_name='streets')
    op.drop_index('idx_streets_name_suff', table_name='streets')
    # ### end Alembic commands ###
