name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `build`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:14-3.2
        ports:
          - 5432/tcp
        # Provide the password for postgres
        env:
          POSTGRES_USER: hello_flask
          POSTGRES_PASSWORD: hello_flask
          POSTGRES_DB: chicagodir_dev
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Install Node dependencies
        run: npm install
      - name: Run Node lints
        run: npm run lint
      - name: Run Python lints
        run: poetry run flask lint --check
        env:
          FLASK_APP: autoapp.py
      - name: Run Python tests
        run: poetry run flask test
        env:
          FLASK_APP: autoapp.py
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
          DATABASE_URL: postgresql://hello_flask:hello_flask@localhost:${POSTGRES_PORT}/chicagodir_dev
