name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Service containers to run with `build`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        ports:
          - 5432/tcp
        # Provide the password for postgres
        env:
          POSTGRES_USER: hello_flask
          POSTGRES_PASSWORD: hello_flask
          POSTGRES_DB: chicagodir_dev
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Install Node dependencies
        run: npm install
      - run: cp .env.example .env
      - name: Run Node lints
        run: npm run lint
      - name: Run Python lints
        run: pipenv run flask lint --check
      - name: Run Python tests
        run: pipenv run flask test
        env: 
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
          POSTGRES_USER: hello_flask
          POSTGRES_PASSWORD: hello_flask
          POSTGRES_DB: chicagodir_dev
